Обновление скринов; исправление работы установки MTU; уточнён порядок установки ipk; проверка версии KeenOS.

diff --git a/blob/02__KeenOS_5.0_(OpkgTun)/S52awg-opkgtun0 b/blob/02__KeenOS_5.0_(OpkgTun)/S52awg-opkgtun0
--- a/blob/02__KeenOS_5.0_(OpkgTun)/S52awg-opkgtun0
+++ b/blob/02__KeenOS_5.0_(OpkgTun)/S52awg-opkgtun0
@@ -1,22 +1,33 @@
 #!/bin/sh
 
-# v2025-12-22 fin
+# v2025-12-25 Fin
 ENABLED=yes
-PROCS="/opt/bin/amneziawg-go"
+PROCS="amneziawg-go"
 PATH="/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
 DESC="AmneziaWG OpkgTun"
 PROGRAM="${0##*/}"
 AWG_BIN="/opt/bin/awg"
+KEENOS_VER_MAJOR=$(ndmc -c "show version" | grep -o 'title: [0-9]' | cut -d' ' -f2)
+KEENOS_VER=$(ndmc -c "show version" | grep -oE 'title: [0-9.]+' | cut -d' ' -f2)
 
 # ================== НАСТРОЙКИ ДЛЯ ПОЛЬЗОВАТЕЛЕЙ ==================
 # Интерфейс OpkgTun
 OPKGTUN_INTERFACE="opkgtun0"
 
+# Размер MTU, применяемый к интерфейсу OpkgTun
+OPKGTUN_MTU="1376"
+
 # Файл конфигурации AWG
 AWG_CONF="/opt/etc/amnezia/amneziawg/awg0-opkgtun0.conf"
 
+
 # Сервер:порт для проверки скорости через iperf3.
-SPEEDTEST_SRV_ADDRESSES="it1.speedtest.aruba.it:5201 mskst.st.mtsws.net:3333"
+SPEEDTEST_SRV_ADDRESSES="
+it1.speedtest.aruba.it:5201
+mskst.st.mtsws.net:3333
+"
+# Время в секундах на тестирование скорости в каждую сторону
+SPEEDTEST_TIME="5"
 # =================================================================
 
 
@@ -25,14 +36,14 @@ cmd_start() {
     check_binary_files
     [ -f "$AWG_CONF" ] || die "⚠️ AWG config-file \e[3m $AWG_CONF \e[0m does not exist!"
 
-    if pgrep -f "$PROCS $OPKGTUN_INTERFACE" > /dev/null; then
+    if pgrep -f "/opt/bin/$PROCS $OPKGTUN_INTERFACE" > /dev/null; then
         log "ℹ️ AmneziaWG for \e[3m$OPKGTUN_INTERFACE\e[0m already running!"
         log "ℹ️ Use \"\e[3m$PROGRAM restart\e[0m\" if you need restart this interface." && echo "" && return 0
     fi
 
     log "ℹ️ Starting AmneziaWG \e[3m$OPKGTUN_INTERFACE\e[0m interface..."
-    logger -t "[Entware AWG-Go][Info]" "Starting AWG for $OPKGTUN_INTERFACE interface..."
-    "$PROCS" "$OPKGTUN_INTERFACE" >/dev/null 2>&1 &
+    logger -t "[Entware AWG-Go][Info]" "Starting AWG for \"$OPKGTUN_INTERFACE\" interface..."
+    "/opt/bin/$PROCS" "$OPKGTUN_INTERFACE" >/dev/null 2>&1 &
 
     local retries=10
     while [ ! -d "/sys/class/net/$OPKGTUN_INTERFACE" ] && [ $retries -gt 0 ]; do
@@ -42,21 +53,26 @@ cmd_start() {
     if [ -d "/sys/class/net/$OPKGTUN_INTERFACE" ]; then
         if ip link set dev "$OPKGTUN_INTERFACE" up; then
             if ("$AWG_BIN" setconf "$OPKGTUN_INTERFACE" "$AWG_CONF") ; then
-                logger -t "[Entware AWG-Go][Info]" "Successfully configured $OPKGTUN_INTERFACE with \"$AWG_CONF\""
-                log "✅ Successfully configured AWG-opkgtun: \e[3m$OPKGTUN_INTERFACE\e[0m"
+                if ip link set dev "$OPKGTUN_INTERFACE" mtu "$OPKGTUN_MTU" 2>/dev/null; then
+                    logger -t "[Entware AWG-Go][Info]" "MTU \"$OPKGTUN_MTU\" successfully set on \"$OPKGTUN_INTERFACE\""
+                else
+                    logger -t "[Entware AWG-Go][Err]" "Failed to set MTU \"$OPKGTUN_MTU\" on \"$OPKGTUN_INTERFACE\""
+                fi
+                logger -t "[Entware AWG-Go][Info]" "Successfully configured \"$OPKGTUN_INTERFACE\" with \"$AWG_CONF\""
+                log "✅ Successfully configured AWG-opkgtun: \e[3m$OPKGTUN_INTERFACE\e[0m  |  MTU \e[3m$OPKGTUN_MTU\e[0m"
                 sleep 2 && echo ""&& cmd_status
             else
                 sleep 2 && cmd_stop
-                logger -t "[Entware AWG-Go][Err]" "Failed to apply config \"$AWG_CONF\" to $OPKGTUN_INTERFACE!"
+                logger -t "[Entware AWG-Go][Err]" "Failed to apply config \"$AWG_CONF\" to \"$OPKGTUN_INTERFACE\"!"
                 die "❌ Failed to apply config \e[3m$AWG_CONF\e[0m to \e[3m$OPKGTUN_INTERFACE\e[0m."
             fi
         else
             cmd_stop
-            logger -t "[Entware AWG-Go][Err]" "Failed to UP network interface $OPKGTUN_INTERFACE!"
+            logger -t "[Entware AWG-Go][Err]" "Failed to UP network interface \"$OPKGTUN_INTERFACE\"!"
             die "❌ Failed to UP network interface \e[3m$OPKGTUN_INTERFACE\e[0m."
         fi
     else
-        logger -t "[Entware AWG-Go][Err]" "Interface $OPKGTUN_INTERFACE did not appear after start!"
+        logger -t "[Entware AWG-Go][Err]" "Interface \"$OPKGTUN_INTERFACE\" did not appear after start!"
         die "❌ Interface \e[3m$OPKGTUN_INTERFACE\e[0m did not appear after start."
     fi
 }
@@ -65,19 +81,19 @@ cmd_start() {
 cmd_stop() {
     check_binary_files
 
-    local AWG_PID=$(pgrep -f "$PROCS $OPKGTUN_INTERFACE")
+    local AWG_PID=$(pgrep -f "/opt/bin/$PROCS $OPKGTUN_INTERFACE")
     if [ -n "$AWG_PID" ]; then
-        logger -t "[Entware AWG-Go][Info]" "Stopping  AWG for $OPKGTUN_INTERFACE with \"$AWG_CONF\"..."
+        logger -t "[Entware AWG-Go][Info]" "Stopping  AWG for \"$OPKGTUN_INTERFACE\" with \"$AWG_CONF\"..."
         log "ℹ️ Stopping AmneziaWG for \e[3m$OPKGTUN_INTERFACE\e[0m (PID: $AWG_PID)..."
         kill "$AWG_PID" > /dev/null 2>&1
 
         local timeout=5
-        while pgrep -f "$PROCS $OPKGTUN_INTERFACE" > /dev/null && [ $timeout -gt 0 ]; do
+        while pgrep -f "/opt/bin/$PROCS $OPKGTUN_INTERFACE" > /dev/null && [ $timeout -gt 0 ]; do
             sleep 1 && timeout=$((timeout - 1))
         done
 
-        if pgrep -f "$PROCS $OPKGTUN_INTERFACE" > /dev/null; then
-            logger -t "[Entware AWG-Go][Warn]" "Process did not respond, forcing termination AWG for $OPKGTUN_INTERFACE..."
+        if pgrep -f "/opt/bin/$PROCS $OPKGTUN_INTERFACE" > /dev/null; then
+            logger -t "[Entware AWG-Go][Warn]" "Process did not respond, forcing termination AWG for \"$OPKGTUN_INTERFACE\"..."
             log "⚠️ Process did not respond, forcing termination... ⚠️"
             kill -9 "$AWG_PID" > /dev/null 2>&1
         fi
@@ -85,7 +101,7 @@ cmd_stop() {
         if [ -d "/sys/class/net/$OPKGTUN_INTERFACE" ]; then
              ip link set dev "$OPKGTUN_INTERFACE" down
         fi
-        logger -t "[Entware AWG-Go][Info]" "AWG for $OPKGTUN_INTERFACE with \"$AWG_CONF\" stopped successfully."
+        logger -t "[Entware AWG-Go][Info]" "AWG for \"$OPKGTUN_INTERFACE\" with \"$AWG_CONF\" stopped successfully."
         log "✅ AmneziaWG for \e[3m$OPKGTUN_INTERFACE\e[0m stopped successfully." && echo ""
     else
         log "ℹ️ AmneziaWG for \e[3m$OPKGTUN_INTERFACE\e[0m is NOT running." && echo ""
@@ -103,16 +119,16 @@ cmd_status() {
     else
         ip -c -br link show dev "$OPKGTUN_INTERFACE"
         
-        if pgrep -f "$PROCS $OPKGTUN_INTERFACE" > /dev/null; then
-            logger -t "[Entware AWG-Go][Info]" "AWG-Go for $OPKGTUN_INTERFACE with \"$AWG_CONF\" running"
+        if pgrep -f "/opt/bin/$PROCS $OPKGTUN_INTERFACE" > /dev/null; then
+            logger -t "[Entware AWG-Go][Info]" "AWG-Go for \"$OPKGTUN_INTERFACE\" with \"$AWG_CONF\" running"
             log "✅ AWG-Go for \e[3m$OPKGTUN_INTERFACE\e[0m running"
             local RAW_LASTHANDSHAKE=$("$AWG_BIN" show "$OPKGTUN_INTERFACE" latest-handshakes 2>/dev/null)
             LASTHANDSHAKE=$(echo "$RAW_LASTHANDSHAKE" | awk '{print $2}' 2>/dev/null)
             if [ -n "$LASTHANDSHAKE" ] && [ "$LASTHANDSHAKE" -ne 0 ] 2>/dev/null; then
-                logger -t "[Entware AWG-Go][Info]" "$OPKGTUN_INTERFACE with \"$AWG_CONF\" Last Handshake: $(date -d "@$LASTHANDSHAKE" '+%Y-%m-%d %H:%M:%S')"
+                logger -t "[Entware AWG-Go][Info]" "\"$OPKGTUN_INTERFACE\" with \"$AWG_CONF\" Last Handshake: $(date -d "@$LASTHANDSHAKE" '+%Y-%m-%d %H:%M:%S')"
                 log "ℹ️ Last Handshake: $(date -d "@$LASTHANDSHAKE" '+%Y-%m-%d %H:%M:%S')"
             else
-                logger -t "[Entware AWG-Go][Warn]" "$OPKGTUN_INTERFACE with \"$AWG_CONF\" Last Handshake: NONE (No connection)"
+                logger -t "[Entware AWG-Go][Warn]" "\"$OPKGTUN_INTERFACE\" with \"$AWG_CONF\" Last Handshake: NONE (No connection)"
                 log "⚠️ Last Handshake: ❌ \e[31mNONE\e[0m (No connection)"
             fi
 
@@ -120,10 +136,10 @@ cmd_status() {
             log "ℹ️ Testing external IP via \e[3m$OPKGTUN_INTERFACE\e[0m..."
             local VPS_IP=$(curl --interface "$OPKGTUN_INTERFACE" -s --max-time 3 ifconfig.me 2>/dev/null)
             if [ -n "$VPS_IP" ]; then
-                logger -t "[Entware AWG-Go][Info]" "External IP via $OPKGTUN_INTERFACE: $VPS_IP"
+                logger -t "[Entware AWG-Go][Info]" "External IP via \"$OPKGTUN_INTERFACE\": $VPS_IP"
                 log "✅ External IP via \e[3m$OPKGTUN_INTERFACE\e[0m: \e[33m$VPS_IP\e[0m"
             else
-                logger -t "[Entware AWG-Go][Warn]" "Failed to obtain external IP via $OPKGTUN_INTERFACE"
+                logger -t "[Entware AWG-Go][Warn]" "Failed to obtain external IP via \"$OPKGTUN_INTERFACE\""
                 log "❌ \e[31mFailed to obtain external IP\e[0m via \e[3m$OPKGTUN_INTERFACE\e[0m"
             fi
         else
@@ -162,26 +178,26 @@ cmd_speedtest () {
 
     if [ ! -d "/sys/class/net/$OPKGTUN_INTERFACE" ]; then
         echo -e "❌ Interface \e[3m$OPKGTUN_INTERFACE\e[0m does NOT exist!"
-        return 1
+        echo "======================================================================" && echo "" && return 1
     fi
 
-    if ! pgrep -f "$PROCS $OPKGTUN_INTERFACE" >/dev/null; then
+    if ! pgrep -f "/opt/bin/$PROCS $OPKGTUN_INTERFACE" >/dev/null; then
         log "⚠️ AmneziaWG for \e[3m$OPKGTUN_INTERFACE\e[0m NOT running!"
         log "ℹ️ Can't run SpeedTest."
-        return 1
+        echo "======================================================================" && echo "" && return 1
     fi
 
     logger -t "[Entware AWG-Go][Info]" \
-        "AWG-Go for $OPKGTUN_INTERFACE with \"$AWG_CONF\" running, begin SpeedTest..."
+        "AWG-Go for \"$OPKGTUN_INTERFACE\" with \"$AWG_CONF\" running, begin SpeedTest..."
     log "✅ AWG-Go for \e[3m$OPKGTUN_INTERFACE\e[0m running, begin SpeedTest..."
 
     OPKGTUN_IP=$(ip -4 -br addr show "$OPKGTUN_INTERFACE" | awk '{print $3}' | cut -d'/' -f1 2>/dev/null)
 
     if [ -z "$OPKGTUN_IP" ]; then
         logger -t "[Entware AWG-Go][Err]" \
-            "Can't obtain $OPKGTUN_INTERFACE IPv4 address. Stopping SpeedTest."
+            "Can't obtain \"$OPKGTUN_INTERFACE\" IPv4 address. Stopping SpeedTest."
         log "❌ \e[31mCan't obtain\e[0m \e[3m$OPKGTUN_INTERFACE\e[0m IPv4 address. Stopping SpeedTest."
-        return 1
+        echo "======================================================================" && echo "" && return 1
     fi
 
     if ! select_speedtest_server; then
@@ -218,13 +234,13 @@ run_speedtest() {
         SPEEDTEST_SRV_ADDR=${srv%%:*}
         SPEEDTEST_SRV_PORT=${srv##*:}
 
-        log "$mode: Trying server \e[3m$SPEEDTEST_SRV_ADDR:$SPEEDTEST_SRV_PORT\e[0m"
+        log "$mode: Trying server \e[3m$SPEEDTEST_SRV_ADDR:$SPEEDTEST_SRV_PORT\e[0m (\e[1;3;31mtest time: $SPEEDTEST_TIME sec.\e[0m)"
 
         OUTPUT=$(iperf3 -c "$SPEEDTEST_SRV_ADDR" \
                          -p "$SPEEDTEST_SRV_PORT" \
                          -B "$interface_ip" \
                          $extra_args \
-                         -t 5 \
+                         -t $SPEEDTEST_TIME \
                          --connect-timeout 3000 \
                          --json 2>&1)
 
@@ -246,8 +262,7 @@ run_speedtest() {
         return 0
     done
 
-    log "$mode: ❌ No working SpeedTest servers"
-    return 1
+    log "$mode: ❌ Failed to check SpeedTest via specified servers" && return 1
 }
 
 
@@ -271,8 +286,9 @@ check_package_installed () {
 
 
 check_binary_files () {
-    [ -x "$PROCS" ] || die "⚠️ Application \e[3m $PROCS \e[0m not found or not executable."
+    [ -x "/opt/bin/$PROCS" ] || die "⚠️ Application \e[3m /opt/bin/$PROCS \e[0m not found or not executable."
     [ -x "$AWG_BIN" ] || die "⚠️ Application \e[3m $AWG_BIN \e[0m not found or not executable."
+    [ "$KEENOS_VER_MAJOR" -lt 5 ] && die "❌ Your KeenOS is \e[3m$KEENOS_VER\e[0m. Version 5.0.2 or higher is required."
 }
 
 
